# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\KIIT\Desktop\Project\TaskScheduler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\KIIT\Desktop\Project\TaskScheduler\build

# Include any dependencies generated for this target.
include CMakeFiles/scheduler.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/scheduler.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/scheduler.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/scheduler.dir/flags.make

CMakeFiles/scheduler.dir/codegen:
.PHONY : CMakeFiles/scheduler.dir/codegen

CMakeFiles/scheduler.dir/src/main.cpp.obj: CMakeFiles/scheduler.dir/flags.make
CMakeFiles/scheduler.dir/src/main.cpp.obj: CMakeFiles/scheduler.dir/includes_CXX.rsp
CMakeFiles/scheduler.dir/src/main.cpp.obj: C:/Users/KIIT/Desktop/Project/TaskScheduler/src/main.cpp
CMakeFiles/scheduler.dir/src/main.cpp.obj: CMakeFiles/scheduler.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/scheduler.dir/src/main.cpp.obj"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/scheduler.dir/src/main.cpp.obj -MF CMakeFiles\scheduler.dir\src\main.cpp.obj.d -o CMakeFiles\scheduler.dir\src\main.cpp.obj -c C:\Users\KIIT\Desktop\Project\TaskScheduler\src\main.cpp

CMakeFiles/scheduler.dir/src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/scheduler.dir/src/main.cpp.i"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\KIIT\Desktop\Project\TaskScheduler\src\main.cpp > CMakeFiles\scheduler.dir\src\main.cpp.i

CMakeFiles/scheduler.dir/src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/scheduler.dir/src/main.cpp.s"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\KIIT\Desktop\Project\TaskScheduler\src\main.cpp -o CMakeFiles\scheduler.dir\src\main.cpp.s

CMakeFiles/scheduler.dir/src/task.cpp.obj: CMakeFiles/scheduler.dir/flags.make
CMakeFiles/scheduler.dir/src/task.cpp.obj: CMakeFiles/scheduler.dir/includes_CXX.rsp
CMakeFiles/scheduler.dir/src/task.cpp.obj: C:/Users/KIIT/Desktop/Project/TaskScheduler/src/task.cpp
CMakeFiles/scheduler.dir/src/task.cpp.obj: CMakeFiles/scheduler.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/scheduler.dir/src/task.cpp.obj"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/scheduler.dir/src/task.cpp.obj -MF CMakeFiles\scheduler.dir\src\task.cpp.obj.d -o CMakeFiles\scheduler.dir\src\task.cpp.obj -c C:\Users\KIIT\Desktop\Project\TaskScheduler\src\task.cpp

CMakeFiles/scheduler.dir/src/task.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/scheduler.dir/src/task.cpp.i"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\KIIT\Desktop\Project\TaskScheduler\src\task.cpp > CMakeFiles\scheduler.dir\src\task.cpp.i

CMakeFiles/scheduler.dir/src/task.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/scheduler.dir/src/task.cpp.s"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\KIIT\Desktop\Project\TaskScheduler\src\task.cpp -o CMakeFiles\scheduler.dir\src\task.cpp.s

CMakeFiles/scheduler.dir/src/scheduler.cpp.obj: CMakeFiles/scheduler.dir/flags.make
CMakeFiles/scheduler.dir/src/scheduler.cpp.obj: CMakeFiles/scheduler.dir/includes_CXX.rsp
CMakeFiles/scheduler.dir/src/scheduler.cpp.obj: C:/Users/KIIT/Desktop/Project/TaskScheduler/src/scheduler.cpp
CMakeFiles/scheduler.dir/src/scheduler.cpp.obj: CMakeFiles/scheduler.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/scheduler.dir/src/scheduler.cpp.obj"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/scheduler.dir/src/scheduler.cpp.obj -MF CMakeFiles\scheduler.dir\src\scheduler.cpp.obj.d -o CMakeFiles\scheduler.dir\src\scheduler.cpp.obj -c C:\Users\KIIT\Desktop\Project\TaskScheduler\src\scheduler.cpp

CMakeFiles/scheduler.dir/src/scheduler.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/scheduler.dir/src/scheduler.cpp.i"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\KIIT\Desktop\Project\TaskScheduler\src\scheduler.cpp > CMakeFiles\scheduler.dir\src\scheduler.cpp.i

CMakeFiles/scheduler.dir/src/scheduler.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/scheduler.dir/src/scheduler.cpp.s"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\KIIT\Desktop\Project\TaskScheduler\src\scheduler.cpp -o CMakeFiles\scheduler.dir\src\scheduler.cpp.s

CMakeFiles/scheduler.dir/src/db_manager.cpp.obj: CMakeFiles/scheduler.dir/flags.make
CMakeFiles/scheduler.dir/src/db_manager.cpp.obj: CMakeFiles/scheduler.dir/includes_CXX.rsp
CMakeFiles/scheduler.dir/src/db_manager.cpp.obj: C:/Users/KIIT/Desktop/Project/TaskScheduler/src/db_manager.cpp
CMakeFiles/scheduler.dir/src/db_manager.cpp.obj: CMakeFiles/scheduler.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/scheduler.dir/src/db_manager.cpp.obj"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/scheduler.dir/src/db_manager.cpp.obj -MF CMakeFiles\scheduler.dir\src\db_manager.cpp.obj.d -o CMakeFiles\scheduler.dir\src\db_manager.cpp.obj -c C:\Users\KIIT\Desktop\Project\TaskScheduler\src\db_manager.cpp

CMakeFiles/scheduler.dir/src/db_manager.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/scheduler.dir/src/db_manager.cpp.i"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\KIIT\Desktop\Project\TaskScheduler\src\db_manager.cpp > CMakeFiles\scheduler.dir\src\db_manager.cpp.i

CMakeFiles/scheduler.dir/src/db_manager.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/scheduler.dir/src/db_manager.cpp.s"
	C:\MinGW\bin\c++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\KIIT\Desktop\Project\TaskScheduler\src\db_manager.cpp -o CMakeFiles\scheduler.dir\src\db_manager.cpp.s

CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj: CMakeFiles/scheduler.dir/flags.make
CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj: CMakeFiles/scheduler.dir/includes_C.rsp
CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj: C:/sqlite/sqlite-amalgamation-3490200/sqlite3.c
CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj: CMakeFiles/scheduler.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj"
	C:\MinGW\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj -MF CMakeFiles\scheduler.dir\C_\sqlite\sqlite-amalgamation-3490200\sqlite3.c.obj.d -o CMakeFiles\scheduler.dir\C_\sqlite\sqlite-amalgamation-3490200\sqlite3.c.obj -c C:\sqlite\sqlite-amalgamation-3490200\sqlite3.c

CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.i"
	C:\MinGW\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\sqlite\sqlite-amalgamation-3490200\sqlite3.c > CMakeFiles\scheduler.dir\C_\sqlite\sqlite-amalgamation-3490200\sqlite3.c.i

CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.s"
	C:\MinGW\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S C:\sqlite\sqlite-amalgamation-3490200\sqlite3.c -o CMakeFiles\scheduler.dir\C_\sqlite\sqlite-amalgamation-3490200\sqlite3.c.s

# Object files for target scheduler
scheduler_OBJECTS = \
"CMakeFiles/scheduler.dir/src/main.cpp.obj" \
"CMakeFiles/scheduler.dir/src/task.cpp.obj" \
"CMakeFiles/scheduler.dir/src/scheduler.cpp.obj" \
"CMakeFiles/scheduler.dir/src/db_manager.cpp.obj" \
"CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj"

# External object files for target scheduler
scheduler_EXTERNAL_OBJECTS =

scheduler.exe: CMakeFiles/scheduler.dir/src/main.cpp.obj
scheduler.exe: CMakeFiles/scheduler.dir/src/task.cpp.obj
scheduler.exe: CMakeFiles/scheduler.dir/src/scheduler.cpp.obj
scheduler.exe: CMakeFiles/scheduler.dir/src/db_manager.cpp.obj
scheduler.exe: CMakeFiles/scheduler.dir/C_/sqlite/sqlite-amalgamation-3490200/sqlite3.c.obj
scheduler.exe: CMakeFiles/scheduler.dir/build.make
scheduler.exe: CMakeFiles/scheduler.dir/linkLibs.rsp
scheduler.exe: CMakeFiles/scheduler.dir/objects1.rsp
scheduler.exe: CMakeFiles/scheduler.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Linking CXX executable scheduler.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\scheduler.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/scheduler.dir/build: scheduler.exe
.PHONY : CMakeFiles/scheduler.dir/build

CMakeFiles/scheduler.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\scheduler.dir\cmake_clean.cmake
.PHONY : CMakeFiles/scheduler.dir/clean

CMakeFiles/scheduler.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" C:\Users\KIIT\Desktop\Project\TaskScheduler C:\Users\KIIT\Desktop\Project\TaskScheduler C:\Users\KIIT\Desktop\Project\TaskScheduler\build C:\Users\KIIT\Desktop\Project\TaskScheduler\build C:\Users\KIIT\Desktop\Project\TaskScheduler\build\CMakeFiles\scheduler.dir\DependInfo.cmake "--color=$(COLOR)"
.PHONY : CMakeFiles/scheduler.dir/depend

